version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=$TYPEORM_PORT
      - TYPEORM_USERNAME=$TYPEORM_USERNAME
      - TYPEORM_PASSWORD=$TYPEORM_PASSWORD
      - TYPEORM_DATABASE=$TYPEORM_DATABASE
      - TYPEORM_SYNCHRONIZE=$TYPEORM_SYNCHRONIZE
    ports: 
      - 3003:3000
  postgres:
    image: postgres
    ports:
      - $TYPEORM_PORT:5432
    environment:
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_DB: $TYPEORM_DATABASE
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db:/var/lib/postgresql/data
    
volumes:
  db: