FROM node:18-alpine
EXPOSE 3000
WORKDIR /app
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY ./src ./src
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./

RUN npm install -g pnpm
RUN pnpm install

RUN npm run build

CMD npm run start